# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 16, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.mainFrame = QtWidgets.QFrame(Form)
        self.mainFrame.setGeometry(QtCore.QRect(620, 90, 750, 680))
        self.mainFrame.setStyleSheet("border: 2px solid white;\n"
"border-radius: 20px;")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.backButton = QtWidgets.QPushButton(self.mainFrame)
        self.backButton.setGeometry(QtCore.QRect(320, 590, 160, 50))
        self.backButton.setStyleSheet("border-image: url(E:/Jia/GUI files/back.png);\n"
"background-color: transparent;")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.exitButton = QtWidgets.QPushButton(self.mainFrame)
        self.exitButton.setGeometry(QtCore.QRect(520, 590, 160, 50))
        self.exitButton.setStyleSheet("border-image: url(E:/Jia/GUI files/exit.png);\n"
"background-color: transparent;")
        self.exitButton.setText("")
        self.exitButton.setObjectName("exitButton")
        self.retryButton = QtWidgets.QPushButton(self.mainFrame)
        self.retryButton.setGeometry(QtCore.QRect(120, 590, 160, 50))
        self.retryButton.setStyleSheet("border-image: url(E:/Jia/GUI files/retry.png);\n"
"background-color: transparent;")
        self.retryButton.setText("")
        self.retryButton.setObjectName("retryButton")
        self.loginButton = QtWidgets.QPushButton(self.mainFrame)
        self.loginButton.setGeometry(QtCore.QRect(280, 460, 250, 75))
        self.loginButton.setStyleSheet("border-image: url(E:/Jia/GUI files/login-empty.png);\n"
"background-color: transparent;")
        self.loginButton.setText("")
        self.loginButton.setObjectName("loginButton")
        self.usernameEntry = QtWidgets.QLineEdit(self.mainFrame)
        self.usernameEntry.setGeometry(QtCore.QRect(260, 130, 300, 60))
        self.usernameEntry.setStyleSheet("border: 2px solid white;\n"
"font: 900 15pt \"Segoe UI Black\";\n"
"border-radius: 20px;\n"
"color:white\n"
"\n"
"")
        self.usernameEntry.setText("")
        self.usernameEntry.setObjectName("usernameEntry")
        self.passwordEntry = QtWidgets.QLineEdit(self.mainFrame)
        self.passwordEntry.setGeometry(QtCore.QRect(260, 250, 300, 60))
        self.passwordEntry.setStyleSheet("border: 2px solid white;\n"
"font: 900 15pt \"Segoe UI Black\";\n"
"border-radius: 20px;\n"
"color:white\n"
"\n"
"")
        self.passwordEntry.setText("")
        self.passwordEntry.setObjectName("passwordEntry")
        self.illegalEntry = QtWidgets.QLabel(self.mainFrame)
        self.illegalEntry.setGeometry(QtCore.QRect(130, 110, 500, 420))
        self.illegalEntry.setPixmap(QtGui.QPixmap("E:/Jia/GUI files/illegalEntry.gif);"))
        self.illegalEntry.setStyleSheet("border: white;\n"
"border-radius: 20px;\n"
"color:white\n"
"\n"
"")
        self.illegalEntry.setText("")
        self.illegalEntry.setObjectName("illegalEntry")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.usernameEntry.setPlaceholderText(_translate("Form", "USERNAME"))
        self.passwordEntry.setPlaceholderText(_translate("Form", "PASSWORD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
