# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainGUIfile(object):
    def setupUi(self, mainGUIfile):
        mainGUIfile.setObjectName("mainGUIfile")
        mainGUIfile.resize(1920, 1080)
        mainGUIfile.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(mainGUIfile)
        self.label.setGeometry(QtCore.QRect(130, 21, 37, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(mainGUIfile)
        self.label_2.setGeometry(QtCore.QRect(650, 140, 900, 600))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:\\Jia\\GUI files\\Hero_Template.gif"))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(mainGUIfile)
        self.pushButton.setGeometry(QtCore.QRect(500, 720, 241, 131))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-image: url(E:/Jia/GUI files/start.png);\n"
"background-color: transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(mainGUIfile)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 720, 241, 131))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-image: url(E:/Jia/GUI files/login.png);\n"
"background-color: transparent;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(mainGUIfile)
        self.pushButton_3.setGeometry(QtCore.QRect(1300, 720, 241, 141))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border-image: url(E:/Jia/GUI files/exit.png);\n"
"background-color: transparent;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(mainGUIfile)
        QtCore.QMetaObject.connectSlotsByName(mainGUIfile)

    def retranslateUi(self, mainGUIfile):
        _translate = QtCore.QCoreApplication.translate
        mainGUIfile.setWindowTitle(_translate("mainGUIfile", "mainGUIfile"))
# import GUI_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGUIfile = QtWidgets.QWidget()
    ui = Ui_mainGUIfile()
    ui.setupUi(mainGUIfile)
    mainGUIfile.show()
    sys.exit(app.exec_())
